In [1]:
import numpy as np

In [2]:
r = np.random.binomial(10, 0.5, size=(10,5))
r

array([[8, 7, 6, 6, 6],
       [3, 3, 4, 5, 2],
       [4, 6, 6, 8, 2],
       [4, 4, 5, 8, 3],
       [5, 5, 2, 5, 5],
       [7, 7, 6, 3, 7],
       [4, 6, 3, 3, 4],
       [6, 7, 4, 7, 7],
       [4, 2, 7, 7, 4],
       [2, 4, 3, 4, 4]])

In [3]:
np.sqrt(r)

array([[2.82842712, 2.64575131, 2.44948974, 2.44948974, 2.44948974],
       [1.73205081, 1.73205081, 2.        , 2.23606798, 1.41421356],
       [2.        , 2.44948974, 2.44948974, 2.82842712, 1.41421356],
       [2.        , 2.        , 2.23606798, 2.82842712, 1.73205081],
       [2.23606798, 2.23606798, 1.41421356, 2.23606798, 2.23606798],
       [2.64575131, 2.64575131, 2.44948974, 1.73205081, 2.64575131],
       [2.        , 2.44948974, 1.73205081, 1.73205081, 2.        ],
       [2.44948974, 2.64575131, 2.        , 2.64575131, 2.64575131],
       [2.        , 1.41421356, 2.64575131, 2.64575131, 2.        ],
       [1.41421356, 2.        , 1.73205081, 2.        , 2.        ]])

In [28]:
a = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 100]])


# a * r

array([ 1,  0,  0,  4,  0,  0,  0,  8,  9, 10])

In [6]:
r[-1]

array([7, 3, 5, 5, 7])

In [2]:
eps=1e-08
eps

1e-08

In [5]:
eps * 10 ** 4

0.0001